# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tyiE5F226PgrN2ZjBIzh-tlw4DSIAmHB
"""

from flask import Flask, render_template, request
import joblib
import numpy as np
import pandas as pd

app = Flask(__name__)

# Load models and scaler
fire_model = joblib.load("fire_resistance_model (1).pkl")
strength_model = joblib.load("compressive_strength_model (1).pkl")
scaler = joblib.load("preprocessor (1).pkl")

# Home page
@app.route("/", methods=["GET", "POST"])
def index():
    prediction = None
    if request.method == "POST":
        try:
            # Extract input values from form
            features = [
                float(request.form["cement"]),
                float(request.form["coarse"]),
                float(request.form["fine"]),
                float(request.form["wcr"]),
                int(request.form["agg_type"]),
                float(request.form["density"]),
                float(request.form["thickness"]),
                int(request.form["fiber"]),
                float(request.form["sfume"])
            ]

            X_input = np.array([features])
            X_scaled = scaler.transform(X_input)

            # Predict
            fire_pred = fire_model.predict(X_scaled)[0]
            strength_pred = strength_model.predict(X_scaled)[0]

            prediction = {
                "fire": round(fire_pred, 2),
                "strength": round(strength_pred, 2)
            }
        except Exception as e:
            prediction = {"error": str(e)}

    return render_template("index.html", prediction=prediction)

if __name__ == "__main__":
    app.run(debug=True)